export const MARKET = {
  "name": "DriveLens Market Lab",
  "classification": "fictional AI-assisted Canadian vehicle marketplace portfolio demonstration",
  "currency": "CAD",
  "distanceUnit": "km",
  "demo": true,
  "disclaimer": "Vehicles, prices, inspection scores, branches, financing examples, reservations and administrative records are fictional. No sale, financing application or test drive is submitted."
};

export const VEHICLES = [
  {
    "id": "veh-arden-nova-e",
    "slug": "arden-nova-e",
    "make": "Arden",
    "model": "Nova E",
    "trim": "Long Range",
    "year": 2025,
    "price": 52900,
    "mileageKm": 6200,
    "bodyType": "Sedan",
    "fuelType": "Electric",
    "transmission": "Single-speed",
    "drivetrain": "AWD",
    "seats": 5,
    "color": "Pearl white",
    "rangeKm": 515,
    "efficiency": "17.2 kWh/100 km",
    "location": "Ottawa, ON",
    "status": "Available",
    "featured": true,
    "image": "/assets/images/vehicles/arden-nova-e.svg",
    "summary": "A quiet long-range electric sedan with winter-ready all-wheel drive.",
    "description": "The fictional Arden Nova E pairs a low-slung cabin with a practical liftback-style trunk, heat-pump climate control and a driver-assistance suite designed for Canadian commuting.",
    "features": [
      "Heat-pump climate control",
      "360\u00b0 camera",
      "Adaptive cruise control",
      "Heated front and rear seats",
      "11 kW AC charging"
    ],
    "inspectionScore": 94,
    "history": "Single-owner demonstration record; no real vehicle history is represented.",
    "branch": "DriveLens Ottawa Lab"
  },
  {
    "id": "veh-kinetic-trail-x",
    "slug": "kinetic-trail-x",
    "make": "Kinetic",
    "model": "Trail X",
    "trim": "Hybrid Touring",
    "year": 2024,
    "price": 46800,
    "mileageKm": 18300,
    "bodyType": "SUV",
    "fuelType": "Hybrid",
    "transmission": "e-CVT",
    "drivetrain": "AWD",
    "seats": 5,
    "color": "Forest green",
    "rangeKm": null,
    "efficiency": "5.7 L/100 km",
    "location": "Toronto, ON",
    "status": "Available",
    "featured": true,
    "image": "/assets/images/vehicles/kinetic-trail-x.svg",
    "summary": "A compact hybrid SUV balanced for urban efficiency and weekend utility.",
    "description": "The fictional Kinetic Trail X offers a flexible cargo floor, all-weather drive modes and a fuel-efficient hybrid system without requiring plug-in charging.",
    "features": [
      "Panoramic roof",
      "Blind-spot monitoring",
      "Wireless phone projection",
      "Power liftgate",
      "Roof rails"
    ],
    "inspectionScore": 91,
    "history": "Synthetic marketplace listing. Verify any real vehicle independently.",
    "branch": "DriveLens Toronto Lab"
  },
  {
    "id": "veh-meridian-corsa",
    "slug": "meridian-corsa",
    "make": "Meridian",
    "model": "Corsa",
    "trim": "Premium",
    "year": 2023,
    "price": 32900,
    "mileageKm": 28400,
    "bodyType": "Sedan",
    "fuelType": "Gasoline",
    "transmission": "8-speed automatic",
    "drivetrain": "FWD",
    "seats": 5,
    "color": "Midnight blue",
    "rangeKm": null,
    "efficiency": "7.1 L/100 km",
    "location": "Ottawa, ON",
    "status": "Available",
    "featured": false,
    "image": "/assets/images/vehicles/meridian-corsa.svg",
    "summary": "A refined midsize sedan with strong comfort and straightforward controls.",
    "description": "The fictional Meridian Corsa focuses on quiet highway travel, supportive seating and a conventional powertrain that is easy to understand and service.",
    "features": [
      "Memory driver's seat",
      "Lane-keeping support",
      "Dual-zone climate",
      "Parking sensors",
      "Acoustic windshield"
    ],
    "inspectionScore": 89,
    "history": "Synthetic listing with no connection to a real VIN or service record.",
    "branch": "DriveLens Ottawa Lab"
  },
  {
    "id": "veh-northline-atlas",
    "slug": "northline-atlas",
    "make": "Northline",
    "model": "Atlas",
    "trim": "Family AWD",
    "year": 2024,
    "price": 57900,
    "mileageKm": 14100,
    "bodyType": "SUV",
    "fuelType": "Gasoline",
    "transmission": "10-speed automatic",
    "drivetrain": "AWD",
    "seats": 7,
    "color": "Graphite",
    "rangeKm": null,
    "efficiency": "10.4 L/100 km",
    "location": "Calgary, AB",
    "status": "Available",
    "featured": true,
    "image": "/assets/images/vehicles/northline-atlas.svg",
    "summary": "A three-row SUV designed around family access, towing and winter traction.",
    "description": "The fictional Northline Atlas includes a wide-opening second row, configurable cargo space and driver aids for long-distance family travel.",
    "features": [
      "7-seat cabin",
      "Tow package",
      "Surround-view camera",
      "Tri-zone climate",
      "Hands-free liftgate"
    ],
    "inspectionScore": 92,
    "history": "Fictional inventory record for portfolio demonstration only.",
    "branch": "DriveLens Calgary Lab"
  },
  {
    "id": "veh-solara-metro",
    "slug": "solara-metro",
    "make": "Solara",
    "model": "Metro",
    "trim": "Urban EV",
    "year": 2025,
    "price": 38900,
    "mileageKm": 3100,
    "bodyType": "Hatchback",
    "fuelType": "Electric",
    "transmission": "Single-speed",
    "drivetrain": "FWD",
    "seats": 5,
    "color": "Coral red",
    "rangeKm": 365,
    "efficiency": "14.9 kWh/100 km",
    "location": "Montreal, QC",
    "status": "Available",
    "featured": false,
    "image": "/assets/images/vehicles/solara-metro.svg",
    "summary": "A compact electric hatchback sized for dense city driving and simple charging.",
    "description": "The fictional Solara Metro prioritizes easy parking, efficient energy use and a bright cabin with fold-flat rear seats.",
    "features": [
      "Heat pump",
      "One-pedal driving",
      "DC fast charging",
      "Heated steering wheel",
      "Rear parking camera"
    ],
    "inspectionScore": 95,
    "history": "Synthetic vehicle and mileage. No real inspection has occurred.",
    "branch": "DriveLens Ottawa Lab"
  },
  {
    "id": "veh-vanta-ridge",
    "slug": "vanta-ridge",
    "make": "Vanta",
    "model": "Ridge",
    "trim": "Crew 4x4",
    "year": 2022,
    "price": 44900,
    "mileageKm": 46800,
    "bodyType": "Pickup",
    "fuelType": "Gasoline",
    "transmission": "8-speed automatic",
    "drivetrain": "4WD",
    "seats": 5,
    "color": "Copper",
    "rangeKm": null,
    "efficiency": "12.6 L/100 km",
    "location": "Calgary, AB",
    "status": "Available",
    "featured": false,
    "image": "/assets/images/vehicles/vanta-ridge.svg",
    "summary": "A midsize crew-cab pickup with a practical bed and selectable four-wheel drive.",
    "description": "The fictional Vanta Ridge is positioned as a utility-focused truck for recreation and light work, with a manageable footprint compared with full-size pickups.",
    "features": [
      "Spray-in bed liner",
      "Trailer brake controller",
      "Hill descent control",
      "Heated seats",
      "Bed power outlet"
    ],
    "inspectionScore": 86,
    "history": "Synthetic listing. Towing and condition claims are illustrative only.",
    "branch": "DriveLens Calgary Lab"
  },
  {
    "id": "veh-aeropulse-gt",
    "slug": "aeropulse-gt",
    "make": "AeroPulse",
    "model": "GT",
    "trim": "Performance",
    "year": 2023,
    "price": 61900,
    "mileageKm": 11900,
    "bodyType": "Coupe",
    "fuelType": "Gasoline",
    "transmission": "6-speed manual",
    "drivetrain": "RWD",
    "seats": 4,
    "color": "Sunset orange",
    "rangeKm": null,
    "efficiency": "10.8 L/100 km",
    "location": "Toronto, ON",
    "status": "Unavailable",
    "featured": false,
    "image": "/assets/images/vehicles/aeropulse-gt.svg",
    "summary": "A rear-drive sport coupe with a manual gearbox and focused cockpit.",
    "description": "The fictional AeroPulse GT is included to demonstrate unavailable inventory and comparison behaviour. No real performance claims are made.",
    "features": [
      "Limited-slip differential",
      "Adaptive dampers",
      "Performance seats",
      "Brembo-style brakes",
      "Track display"
    ],
    "inspectionScore": 90,
    "history": "Fictional vehicle currently unavailable for test-drive planning.",
    "branch": "DriveLens Toronto Lab"
  },
  {
    "id": "veh-everfield-voyage",
    "slug": "everfield-voyage",
    "make": "Everfield",
    "model": "Voyage",
    "trim": "Family Plus",
    "year": 2024,
    "price": 51900,
    "mileageKm": 22100,
    "bodyType": "Minivan",
    "fuelType": "Hybrid",
    "transmission": "e-CVT",
    "drivetrain": "FWD",
    "seats": 8,
    "color": "Silver",
    "rangeKm": null,
    "efficiency": "6.6 L/100 km",
    "location": "Ottawa, ON",
    "status": "Available",
    "featured": false,
    "image": "/assets/images/vehicles/everfield-voyage.svg",
    "summary": "An eight-seat hybrid minivan with sliding doors and flexible storage.",
    "description": "The fictional Everfield Voyage centres accessibility, family seating and lower fuel use for school runs and long-distance travel.",
    "features": [
      "Dual power sliding doors",
      "8-seat layout",
      "Cabin camera",
      "Rear climate controls",
      "Fold-flat third row"
    ],
    "inspectionScore": 93,
    "history": "Synthetic family vehicle listing for product demonstration.",
    "branch": "DriveLens Ottawa Lab"
  },
  {
    "id": "veh-lucent-city",
    "slug": "lucent-city",
    "make": "Lucent",
    "model": "City",
    "trim": "Hybrid SE",
    "year": 2021,
    "price": 24900,
    "mileageKm": 53200,
    "bodyType": "Hatchback",
    "fuelType": "Hybrid",
    "transmission": "e-CVT",
    "drivetrain": "FWD",
    "seats": 5,
    "color": "Sky blue",
    "rangeKm": null,
    "efficiency": "4.8 L/100 km",
    "location": "Halifax, NS",
    "status": "Available",
    "featured": false,
    "image": "/assets/images/vehicles/lucent-city.svg",
    "summary": "A fuel-efficient compact hatchback for commuters and first-time buyers.",
    "description": "The fictional Lucent City combines a small exterior footprint with a versatile cargo area and uncomplicated hybrid operation.",
    "features": [
      "Automatic emergency braking",
      "Keyless entry",
      "Heated seats",
      "60/40 rear seats",
      "Eco drive display"
    ],
    "inspectionScore": 84,
    "history": "Synthetic higher-mileage listing; independent inspection would be essential in a real purchase.",
    "branch": "DriveLens Toronto Lab"
  },
  {
    "id": "veh-terrapeak-cross",
    "slug": "terrapeak-cross",
    "make": "TerraPeak",
    "model": "Cross",
    "trim": "Adventure",
    "year": 2023,
    "price": 39700,
    "mileageKm": 33600,
    "bodyType": "SUV",
    "fuelType": "Gasoline",
    "transmission": "8-speed automatic",
    "drivetrain": "AWD",
    "seats": 5,
    "color": "Sand",
    "rangeKm": null,
    "efficiency": "8.9 L/100 km",
    "location": "Vancouver, BC",
    "status": "Sold",
    "featured": false,
    "image": "/assets/images/vehicles/terrapeak-cross.svg",
    "summary": "A compact AWD crossover with durable interior materials and trail-oriented styling.",
    "description": "The fictional TerraPeak Cross demonstrates sold inventory. It remains viewable for comparison but cannot be added to a new test-drive plan.",
    "features": [
      "All-terrain drive modes",
      "Roof rails",
      "Washable cargo mat",
      "Hill descent control",
      "Full-size spare"
    ],
    "inspectionScore": 88,
    "history": "Synthetic sold record retained for interface demonstration.",
    "branch": "DriveLens Calgary Lab"
  },
  {
    "id": "veh-ionix-stream",
    "slug": "ionix-stream",
    "make": "Ionix",
    "model": "Stream",
    "trim": "Dual Motor",
    "year": 2025,
    "price": 64800,
    "mileageKm": 4800,
    "bodyType": "Crossover",
    "fuelType": "Electric",
    "transmission": "Single-speed",
    "drivetrain": "AWD",
    "seats": 5,
    "color": "Ice grey",
    "rangeKm": 485,
    "efficiency": "18.1 kWh/100 km",
    "location": "Toronto, ON",
    "status": "Available",
    "featured": true,
    "image": "/assets/images/vehicles/ionix-stream.svg",
    "summary": "A quick-charging electric crossover with a spacious flat-floor cabin.",
    "description": "The fictional Ionix Stream combines long-distance charging capability with a flexible crossover shape and all-wheel-drive traction.",
    "features": [
      "800V fast charging",
      "Vehicle-to-load outlet",
      "Remote parking assist",
      "Heat pump",
      "Recycled interior materials"
    ],
    "inspectionScore": 96,
    "history": "Synthetic near-new EV listing for demonstration only.",
    "branch": "DriveLens Toronto Lab"
  },
  {
    "id": "veh-redwood-touring",
    "slug": "redwood-touring",
    "make": "Redwood",
    "model": "Touring",
    "trim": "Cross Country",
    "year": 2022,
    "price": 41800,
    "mileageKm": 39700,
    "bodyType": "Wagon",
    "fuelType": "Gasoline",
    "transmission": "8-speed automatic",
    "drivetrain": "AWD",
    "seats": 5,
    "color": "Burgundy",
    "rangeKm": null,
    "efficiency": "9.1 L/100 km",
    "location": "Ottawa, ON",
    "status": "Available",
    "featured": false,
    "image": "/assets/images/vehicles/redwood-touring.svg",
    "summary": "A raised AWD wagon with long-roof cargo space and highway comfort.",
    "description": "The fictional Redwood Touring offers an alternative to an SUV, pairing a lower loading height with a generous rear cargo area.",
    "features": [
      "Integrated booster cushions",
      "Adaptive headlights",
      "Roof rails",
      "Heated windshield",
      "Driver memory"
    ],
    "inspectionScore": 90,
    "history": "Synthetic vehicle listing; verify recalls and service history in any real transaction.",
    "branch": "DriveLens Ottawa Lab"
  }
];

export const BRANCHES = [
  {
    "id": "ottawa",
    "name": "DriveLens Ottawa Lab",
    "city": "Ottawa",
    "province": "ON",
    "address": "100 Demo Parkway, Ottawa, ON",
    "phone": "613-555-0142",
    "hours": {
      "Monday": "09:00\u201318:00",
      "Tuesday": "09:00\u201318:00",
      "Wednesday": "09:00\u201318:00",
      "Thursday": "09:00\u201319:00",
      "Friday": "09:00\u201318:00",
      "Saturday": "10:00\u201316:00",
      "Sunday": "Closed"
    }
  },
  {
    "id": "toronto",
    "name": "DriveLens Toronto Lab",
    "city": "Toronto",
    "province": "ON",
    "address": "220 Sample Avenue, Toronto, ON",
    "phone": "416-555-0188",
    "hours": {
      "Monday": "09:00\u201318:00",
      "Tuesday": "09:00\u201318:00",
      "Wednesday": "09:00\u201318:00",
      "Thursday": "09:00\u201319:00",
      "Friday": "09:00\u201318:00",
      "Saturday": "10:00\u201316:00",
      "Sunday": "Closed"
    }
  },
  {
    "id": "calgary",
    "name": "DriveLens Calgary Lab",
    "city": "Calgary",
    "province": "AB",
    "address": "45 Prototype Trail, Calgary, AB",
    "phone": "403-555-0161",
    "hours": {
      "Monday": "09:00\u201318:00",
      "Tuesday": "09:00\u201318:00",
      "Wednesday": "09:00\u201318:00",
      "Thursday": "09:00\u201319:00",
      "Friday": "09:00\u201318:00",
      "Saturday": "10:00\u201316:00",
      "Sunday": "Closed"
    }
  }
];
